# Generated by Django 4.1.5 on 2023-06-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.TextField()),
                ('en_uso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinopsis', models.TextField()),
                ('pais', models.CharField(max_length=50)),
                ('duracion', models.PositiveIntegerField()),
                ('fecha_estreno', models.DateField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.pelicula')),
            ],
        ),
    ]
