# Generated by Django 4.1.5 on 2023-06-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_pelicula_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionpelicula',
            old_name='pais',
            new_name='director',
        ),
    ]
