# Generated by Django 4.1.5 on 2023-06-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_pais_informacionpelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpelicula',
            name='duracion',
            field=models.CharField(max_length=10),
        ),
    ]
